apiVersion: v1
kind: Service
metadata:
   name: mongodb-service
   labels:
     run: mongodb-service
spec:
    selector:
      app: mongodb
    clusterIP: None
    ports:
    - port: 27017
      targetPort: 27017